/** 千问 qwen3-tts 非实时音色（与后端 qianwen/voices.go 同词表） */
export const QIANWEN_VOICES: { value: string; label: string }[] = [
  { value: "Cherry", label: "Cherry · 阳光亲切（女）" },
  { value: "Serena", label: "Serena · 温柔（女）" },
  { value: "Ethan", label: "Ethan · 阳光北方（男）" },
  { value: "Chelsie", label: "Chelsie · 二次元（女）" },
  { value: "Momo", label: "Momo · 撒娇搞怪（女）" },
  { value: "Vivian", label: "Vivian · 可爱小暴躁（女）" },
  { value: "Moon", label: "Moon · 率性帅气（男）" },
  { value: "Maia", label: "Maia · 知性温柔（女）" },
  { value: "Kai", label: "Kai · 舒缓悦耳（男）" },
  { value: "Nofish", label: "Nofish · 设计师（男）" },
  { value: "Bella", label: "Bella · 小萝莉（女）" },
  { value: "Jennifer", label: "Jennifer · 电影质感美语（女）" },
  { value: "Ryan", label: "Ryan · 戏感炸裂（男）" },
  { value: "Katerina", label: "Katerina · 御姐韵律（女）" },
  { value: "Aiden", label: "Aiden · 美语大男孩（男）" },
  { value: "Eldric Sage", label: "Eldric Sage · 沉稳老者（男）" },
  { value: "Mia", label: "Mia · 温顺乖巧（女）" },
  { value: "Mochi", label: "Mochi · 早慧小大人（男）" },
  { value: "Bellona", label: "Bellona · 江湖豪情（女）" },
  { value: "Vincent", label: "Vincent · 沙哑烟嗓（男）" },
  { value: "Bunny", label: "Bunny · 萌小萝莉（女）" },
  { value: "Neil", label: "Neil · 新闻主持（男）" },
  { value: "Elias", label: "Elias · 知识讲解（女）" },
  { value: "Arthur", label: "Arthur · 乡村老者（男）" },
  { value: "Nini", label: "Nini · 软黏甜嗓（女）" },
  { value: "Seren", label: "Seren · 温和助眠（女）" },
  { value: "Pip", label: "Pip · 调皮童真（男）" },
  { value: "Stella", label: "Stella · 甜腻少女（女）" },
  { value: "Bodega", label: "Bodega · 西班牙大叔（男）" },
  { value: "Sonrisa", label: "Sonrisa · 拉美大姐（女）" },
  { value: "Alek", label: "Alek · 俄罗斯风（男）" },
  { value: "Dolce", label: "Dolce · 慵懒意大利（男）" },
  { value: "Sohee", label: "Sohee · 韩国欧尼（女）" },
  { value: "Ono Anna", label: "Ono Anna · 青梅竹马（女）" },
  { value: "Lenn", label: "Lenn · 德国青年（男）" },
  { value: "Emilien", label: "Emilien · 浪漫法国（男）" },
  { value: "Andre", label: "Andre · 磁性沉稳（男）" },
  { value: "Radio Gol", label: "Radio Gol · 足球解说（男）" },
  { value: "Jada", label: "Jada · 沪上阿姐（上海话）" },
  { value: "Dylan", label: "Dylan · 胡同少年（北京话）" },
  { value: "Li", label: "Li · 瑜伽老师（南京话）" },
  { value: "Marcus", label: "Marcus · 老陕（陕西话）" },
  { value: "Roy", label: "Roy · 台湾哥仔（闽南语）" },
  { value: "Peter", label: "Peter · 天津捧哏（天津话）" },
  { value: "Sunny", label: "Sunny · 川妹子（四川话）" },
  { value: "Eric", label: "Eric · 成都男子（四川话）" },
  { value: "Rocky", label: "Rocky · 粤语阿强（男）" },
  { value: "Kiki", label: "Kiki · 港妹（女）" },
];

export const QIANWEN_DEFAULT_VOICE = "Cherry";
